### ISSUE TITLE
outdated dependencies

### ISSUE THREAD

**Issue by Amialc** [auth0-samples/auth0-rubyonrails-sample#12]
Sample using [outdated version](https://github.com/auth0-samples/auth0-rubyonrails-sample/blob/master/01-Login/Gemfile#L34) `omniauth-auth0` v1.4.1 (up-to-date version is 2.0.0) and auth0-lock v10.0 (up-to-date version is 10.10). (AUTH-3758)

**Comment by jimmyjames** [comment]
Hi @Amialc, as the libraries you mentioned have been updated in this sample, I'm closing this issue. Don't hesitate to open a new issue if you encounter any difficulties, thanks!
