### ISSUE TITLE
callback_url into multi tenant app

### ISSUE THREAD

**Issue by davidesantangelo** [auth0-samples/auth0-rubyonrails-sample#14]
i want to do this:

`provider(
    :auth0,
    ENV['AUTH0_FRONTEND_CLIENT_ID'],
    ENV['AUTH0_FRONTEND_SECRET'],
    ENV['AUTH0_DOMAIN'],
    callback_path: "/:tenant/auth/auth0/callback",
  )`

is possible?

**Comment by jimmyjames** [comment]
Hi @davidesantangelo, if you still have this question please reopen this issue, or create a new one.
