### ISSUE TITLE
Outdated Lock version

### ISSUE THREAD

**Issue by HeikerAraujo** [auth0-samples/auth0-rubyonrails-sample#17]
Projects are using an oudated Lock version (10.0.0)
Latest Lock version is: 10.16.0

![image](https://cloud.githubusercontent.com/assets/26749061/26509960/27553694-4229-11e7-8b0e-e98cbda0b47f.png)

**Comment by rmcloughlin** [comment]
The problem is even worse now.  Lock was downgraded to 8.8 in this commit:  https://github.com/auth0-samples/auth0-rubyonrails-sample/commit/07e21b6d4cdf0ede23d7fa1617a2c740a5d9aea6
