### ISSUE TITLE
Regular Web App Ruby On Rails Testing: getting multiples errors after bundle install.

### ISSUE THREAD

**Issue by HeikerAraujo** [auth0-samples/auth0-rubyonrails-sample#20]
Regular Web App Ruby On Rails Testing:

After 'bundle install' execution, the console shows the errors belows:

![image](https://user-images.githubusercontent.com/26749061/29030449-06916f9a-7b59-11e7-8080-b9b3d4f75ac3.png)

**Comment by jimmyjames** [comment]
Hi @HeikerAraujo, I'm closing this issue as it's pretty old and the sample has changed since reporting - if you are still experiencing this issue, please reopen.
