### ISSUE TITLE
Docker run issue

### ISSUE THREAD

**Issue by crojas** [auth0-samples/auth0-rubyonrails-sample#32]
i run: docker run -p 3000:3000 auth0-rubyonrails-01

that gives me:

No such file or directory

**Comment by jimmyjames** [comment]
You can run with Docker following the instructions in the [README](https://github.com/auth0-samples/auth0-rubyonrails-sample/tree/master/01-Login#running-the-sample-application-with-docker). If you're still experiencing issues, please reopen this issue or create a new one.
