### ISSUE TITLE
sqlite3 error

### ISSUE THREAD

**Issue by MozyOk** [auth0-samples/auth0-rubyonrails-sample#33]
Thank you for the great example!
I have one error. 
`Gem::LoadError: Specified 'sqlite3' for database adapter, but the gem is not loaded`

### How to fix
add sqlite3 version for Gemfile
`gem 'sqlite3', '~> 1.3.13'`

I'm glad if you can use it as a reference.

**Comment by joshcanhelp** [comment]
This was fixed in #36
