### ISSUE TITLE
Example not working anymore

### ISSUE THREAD

**Issue by foeken** [auth0-samples/auth0-rubyonrails-sample#46]
gem 'omniauth-rails_csrf_protection', '~> 0.1' needed to be updated to 1.0 in order to work again, else I got token errors.

**Comment by davidpatrick** [comment]
I will take a look at this @foeken thanks for raising

**Comment by davidpatrick** [comment]
Yes it looks like a [patch release ](https://github.com/omniauth/omniauth-oauth2/releases/tag/v1.7.1) to `omniauth-oauth2` caused the underlying `omniauth` to get bumped from `1.x` to `2.0.1`.

I will review this today

**Comment by davidpatrick** [comment]
We've released `omniauth-auth0 2.4.2` to address the issue

**Comment by foeken** [comment]
Awesome! Thanks for the amazingly quick fix and reply 🥳
